using System.Security.Claims;
using System.Text;
using BuildingBlocks.Authentication.ServiceTokens;
using BuildingBlocks.Authorization;
using BuildingBlocks.Context;
using BuildingBlocks.FlowClient;
using Contracts;
using Liens.Api.Endpoints;
using Liens.Api.HostedServices;
using Liens.Api.Middleware;
using Liens.Api;
using Liens.Domain;
using Liens.Infrastructure;
using Liens.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

const string ServiceName = "liens";
const string Version = "v1";

var builder = WebApplication.CreateBuilder(args);

builder.Logging
    .ClearProviders()
    .AddConsole();

var jwtSection = builder.Configuration.GetSection("Jwt");
var signingKey = jwtSection["SigningKey"]
    ?? throw new InvalidOperationException("Jwt:SigningKey is not configured.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.MapInboundClaims = false;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer           = true,
            ValidateAudience         = true,
            ValidateLifetime         = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer              = jwtSection["Issuer"],
            ValidAudience            = jwtSection["Audience"],
            IssuerSigningKey         = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey)) { KeyId = ServiceTokenAuthenticationDefaults.UserTokenKeyId },
            RoleClaimType            = "role",
            ClockSkew                = TimeSpan.Zero
        };
    })
    .AddServiceTokenBearer(
        builder.Configuration,
        audience: "liens-service",
        failFastIfMissingSecret: false);

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy(Policies.AuthenticatedUser, policy =>
        policy.RequireAuthenticatedUser());

    options.AddPolicy(Policies.AdminOnly, policy =>
        policy.RequireRole(Roles.PlatformAdmin));

    options.AddPolicy(Policies.PlatformOrTenantAdmin, policy =>
        policy.RequireRole(Roles.PlatformAdmin, Roles.TenantAdmin));
    options.AddPolicy("SynqLienInternal", policy =>
    {
        policy.AddAuthenticationSchemes(ServiceTokenAuthenticationDefaults.Scheme);
        policy.RequireAuthenticatedUser();
        policy.RequireRole(ServiceTokenAuthenticationDefaults.ServiceRole);
    });
});

builder.WebHost.ConfigureKestrel(options =>
{
    options.Limits.MaxRequestBodySize = LiensUploadLimits.MultipartRequestBytes;
});
builder.Services.Configure<FormOptions>(options =>
{
    options.MultipartBodyLengthLimit = LiensUploadLimits.MultipartRequestBytes;
});

builder.Services.AddLiensServices(builder.Configuration);
builder.Services.AddSingleton<AutoGeneratedReportExportConcurrencyLimiter>();
builder.Services.AddHostedService<ScheduledLawFirmSwitchHostedService>();
builder.Services.AddHostedService<WeeklyAutoGeneratedReportHostedService>();
builder.Services.AddHttpClient("Identity", client =>
{
    var baseUrl = builder.Configuration["ExternalServices:Identity:BaseUrl"];
    if (Uri.TryCreate(baseUrl, UriKind.Absolute, out var identityBaseUri))
        client.BaseAddress = identityBaseUri;

    client.Timeout = TimeSpan.FromSeconds(5);
});
builder.Services.AddHttpClient("MedicareProcedureLookup", client =>
{
    client.BaseAddress = new Uri("https://www.medicare.gov/api/procedure-price-lookup/api/v1/core/");
    client.Timeout     = TimeSpan.FromSeconds(20);
});
// LS-FLOW-MERGE-P4 — shared Flow HTTP adapter (bearer pass-through, retry, 503 mapping).
builder.Services.AddFlowClient(builder.Configuration, serviceName: "synqlien");

var app = builder.Build();
var legacyUpdateHistoryEnabled =
    builder.Configuration.GetValue<bool>("LegacyUpdateHistory:Enabled");

var env = app.Environment.EnvironmentName;
app.Logger.LogInformation("Starting {Service} {Version} in {Environment}", ServiceName, Version, env);

// Auto-migrate — apply pending EF Core migrations in all environments (not just Development).
// __EFMigrationsHistory tracks applied migrations; idempotent across restarts and re-deploys.
var initialMigrationFailed = false;
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    await db.Database.MigrateAsync();
    app.Logger.LogInformation("Liens database migrations applied successfully.");
}
catch (Exception ex)
{
    initialMigrationFailed = true;
    app.Logger.LogWarning(ex, "Could not apply Liens database migrations on startup — schema may be out of sync.");
}

// Repair selling schema drift even when migration history was recorded before
// MySQL finished all non-transactional DDL. Normal startups perform read-only
// checks and skip the guarded recovery operations.
var sellingSchemaRepaired = false;
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    sellingSchemaRepaired = await Liens.Infrastructure.Persistence.Migrations.SellingSchemaRepair.EnsureAsync(db, app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogWarning(ex, "Selling schema recovery could not complete — selling APIs may be unavailable.");
}

// Replay the guarded legacy update-event DDL independently of migration
// history. This repairs deployments where MySQL completed only part of the
// non-transactional migration or an earlier pending migration blocked it.
var legacyUpdateEventMigrationWasPending = false;
var legacyUpdateEventSchemaRecoveryRequired = false;
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    legacyUpdateEventSchemaRecoveryRequired = db.Database.IsRelational();
    if (legacyUpdateEventSchemaRecoveryRequired)
    {
        legacyUpdateEventMigrationWasPending =
            await Liens.Infrastructure.Persistence.Migrations.LegacyUpdateEventSchemaRepair.EnsureAsync(
                db,
                app.Logger);
    }
}
catch (Exception ex)
{
    if (legacyUpdateHistoryEnabled && legacyUpdateEventSchemaRecoveryRequired)
    {
        app.Logger.LogCritical(
            ex,
            "Legacy update-event schema recovery failed while imported history reads are enabled.");
        throw;
    }

    app.Logger.LogWarning(
        ex,
        "Legacy update-event schema recovery could not complete — imported history remains unavailable.");
}

// A partially applied MySQL migration can block the first migration pass. Once
// guarded schema recovery repairs that state, retry so EF can record the repaired
// migration and continue to later migrations such as AddAutoGeneratedReports.
if (initialMigrationFailed || sellingSchemaRepaired || legacyUpdateEventMigrationWasPending)
{
    try
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
        await db.Database.MigrateAsync();
        app.Logger.LogInformation("Liens database migrations applied successfully after schema recovery.");
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(
            ex,
            "Could not apply Liens database migrations after schema recovery — schema may still be out of sync.");
    }
}

// Replay the guarded auto-generated-report DDL independently of migration
// history. This also repairs environments where history was recorded after
// only part of MySQL's non-transactional DDL completed.
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    await Liens.Infrastructure.Persistence.Migrations.AutoGeneratedReportSchemaRepair.EnsureAsync(
        db,
        app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogWarning(
        ex,
        "Auto-generated report schema recovery could not complete — report metadata APIs may be unavailable.");
}

// Replay the guarded selling portal message-attachment DDL independently of
// migration history. This repairs deployments where EF did not reach the latest
// migration or MySQL only partially applied its non-transactional DDL.
var sellingPortalMessageAttachmentSchemaRepaired = false;
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    sellingPortalMessageAttachmentSchemaRepaired =
        await Liens.Infrastructure.Persistence.Migrations.SellingPortalMessageAttachmentSchemaRepair.EnsureAsync(
            db,
            app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogWarning(
        ex,
        "Selling portal message-attachment schema recovery could not complete — offer-thread attachments may be unavailable.");
}

if (sellingPortalMessageAttachmentSchemaRepaired)
{
    try
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
        await db.Database.MigrateAsync();
        app.Logger.LogInformation("Liens database migrations applied successfully after message-attachment schema recovery.");
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(
            ex,
            "Could not apply Liens database migrations after message-attachment schema recovery — schema may still be out of sync.");
    }
}

// ── Migration coverage self-test ─────────────────────────────────────────
// Compares every EF-mapped column against the live schema and logs an ERROR
// if any are missing. Catches the class of bug behind Task #58: a migration
// committed without its [Migration] attribute (or otherwise un-applied)
// leaves the EF model and the live schema out of sync, which previously
// surfaced only as runtime "Unknown column" SQL errors.
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    await BuildingBlocks.Diagnostics.MigrationCoverageProbe.RunAsync(db, app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogWarning(ex, "Migration coverage self-test could not run");
}

// ── Schema safety-net ─────────────────────────────────────────────────────
// Creates any tables that were pre-seeded in __EFMigrationsHistory without
// their DDL actually running in production (same pattern as the notifications
// fix). Idempotent: uses CREATE TABLE IF NOT EXISTS so safe on every restart.
try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
    await EnsureLiensSchemaTablesAsync(db, app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogWarning(ex, "EnsureLiensSchemaTablesAsync could not run — schema may be missing tables.");
}

app.UseMiddleware<ExceptionHandlingMiddleware>();
app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/health", () =>
    Results.Ok(new HealthResponse("ok", ServiceName)))
    .AllowAnonymous();

app.MapGet("/info", () =>
    Results.Ok(new InfoResponse(ServiceName, env, Version)))
    .AllowAnonymous();

app.MapGet("/context", (ICurrentRequestContext ctx) =>
{
    if (!ctx.IsAuthenticated)
        return Results.Unauthorized();

    return Results.Ok(new
    {
        authenticated = true,
        userId        = ctx.UserId,
        tenantId      = ctx.TenantId,
        tenantCode    = ctx.TenantCode,
        email         = ctx.Email,
        orgId         = ctx.OrgId,
        orgType       = ctx.OrgType,
        orgTypeId     = ctx.OrgTypeId,
        roles         = ctx.Roles,
        productRoles  = ctx.ProductRoles,
        permissions   = ctx.Permissions,
        isPlatformAdmin = ctx.IsPlatformAdmin,
        capabilities = new
        {
            sell = ctx.CanSellLiens(),
            manageInternal = ctx.CanManageLiensInternal(),
            resolved = ctx.GetLiensCapabilities(),
        },
    });
})
.RequireAuthorization(Policies.AuthenticatedUser);

app.MapSynqLienInternalEndpoints();
app.MapSynqLienUserManagementEndpoints();
app.MapLienEndpoints();
app.MapLegacyDocumentLinkEndpoints();
app.MapAssistantToolEndpoints();
app.MapLienOfferEndpoints();
app.MapSellingPublicEndpoints();
app.MapSellingEndpoints();
app.MapSellingV2Endpoints();
app.MapSellingCompanyEndpoints();
app.MapSellingAnalyticsEndpoints();
app.MapBillOfSaleEndpoints();
app.MapBatchUploadEndpoints();
app.MapCaseEndpoints();
// LS-LIENS-CASE-005 — Case Notes Backend & Persistence.
app.MapCaseNoteEndpoints();
app.MapServicingEndpoints();
app.MapContactEndpoints();
app.MapFacilityEndpoints();
app.MapSettlementEndpoints();
app.MapCasePaymentEndpoints();
app.MapServiceLegacyEndpoints();
app.MapReportEndpoints();
app.MapCaseNotesHistoryReportEndpoints();
app.MapAutoGeneratedReportEndpoints();
// Lookup reference data (states, accident types, contact types, lien statuses, etc.)
app.MapLookupEndpoints();
// LS-FLOW-MERGE-P4 — product → Flow integration endpoints.
app.MapWorkflowEndpoints();
// LS-LIENS-FLOW-001 — My Tasks + Workflow Configuration.
app.MapTaskEndpoints();
app.MapWorkflowConfigEndpoints();
// LS-LIENS-FLOW-002 — Contextual Task Intelligence: Task Templates.
app.MapTaskTemplateEndpoints();
// LS-LIENS-FLOW-003 — Event-Driven Task Generation.
app.MapTaskGenerationRuleEndpoints();
// LS-LIENS-FLOW-004 — Task Notes & Collaboration.
app.MapTaskNoteEndpoints();
// LS-LIENS-FLOW-006 — Task Creation Governance + Email Notifications.
app.MapTaskGovernanceEndpoints();
// LS-LIENS-FLOW-009 — Flow Event Consumption (internal event ingestion).
app.MapFlowEventsEndpoints();
// TASK-B04 — one-shot admin task backfill (internal, shared-secret protected).
app.MapLienTaskBackfillEndpoints();

app.Run();

// ── EnsureLiensSchemaTablesAsync ─────────────────────────────────────────
// Idempotently creates tables that are defined in EF migrations but may not
// have been applied to the live DB (production schema-drift guard).
static async Task EnsureLiensSchemaTablesAsync(LiensDbContext db, ILogger logger)
{
    var conn = db.Database.GetDbConnection();
    if (conn.State != System.Data.ConnectionState.Open)
        await conn.OpenAsync();

    // liens_WorkflowTransitions — added by migration 20260418200000
    const string createWorkflowTransitions = """
        CREATE TABLE IF NOT EXISTS `liens_WorkflowTransitions` (
            `Id`               char(36)    NOT NULL COLLATE ascii_general_ci,
            `WorkflowConfigId` char(36)    NOT NULL COLLATE ascii_general_ci,
            `FromStageId`      char(36)    NOT NULL COLLATE ascii_general_ci,
            `ToStageId`        char(36)    NOT NULL COLLATE ascii_general_ci,
            `IsActive`         tinyint(1)  NOT NULL,
            `SortOrder`        int         NOT NULL,
            `CreatedByUserId`  char(36)    NOT NULL COLLATE ascii_general_ci,
            `UpdatedByUserId`  char(36)    NULL     COLLATE ascii_general_ci,
            `CreatedAtUtc`     datetime(6) NOT NULL,
            `UpdatedAtUtc`     datetime(6) NOT NULL,
            PRIMARY KEY (`Id`),
            CONSTRAINT `FK_lWT_WorkflowConfigId`
                FOREIGN KEY (`WorkflowConfigId`) REFERENCES `liens_WorkflowConfigs` (`Id`) ON DELETE CASCADE,
            CONSTRAINT `FK_lWT_FromStageId`
                FOREIGN KEY (`FromStageId`) REFERENCES `liens_WorkflowStages` (`Id`) ON DELETE RESTRICT,
            CONSTRAINT `FK_lWT_ToStageId`
                FOREIGN KEY (`ToStageId`) REFERENCES `liens_WorkflowStages` (`Id`) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        """;

    // TASK-MIG-09: liens_TaskGovernanceSettings removed — table dropped by migration 20260421000002.
    // TASK-MIG-09: liens_TaskTemplates removed — table dropped by migration 20260421000002.

    using var cmd = conn.CreateCommand();
    cmd.CommandText = createWorkflowTransitions;
    await cmd.ExecuteNonQueryAsync();
    logger.LogInformation("EnsureLiensSchemaTablesAsync: liens_WorkflowTransitions ensured.");

    // LS-LIENS-FLOW-007 — liens_Tasks.WorkflowInstanceId + WorkflowStepKey columns
    // Added by migration 20260420000002_AddTaskFlowLinkage. MySQL does not support
    // ADD COLUMN IF NOT EXISTS, so we guard via information_schema.
    cmd.CommandText = """
        SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME   = 'liens_Tasks'
          AND COLUMN_NAME  = 'WorkflowInstanceId'
        """;
    var hasWorkflowInstanceId = Convert.ToInt64(await cmd.ExecuteScalarAsync()) > 0;

    if (!hasWorkflowInstanceId)
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Tasks`
                ADD COLUMN `WorkflowInstanceId` char(36)     NULL COLLATE ascii_general_ci,
                ADD COLUMN `WorkflowStepKey`    varchar(200) NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added WorkflowInstanceId/WorkflowStepKey to liens_Tasks.");

        try
        {
            cmd.CommandText = "CREATE INDEX `IX_Tasks_TenantId_WorkflowInstanceId` ON `liens_Tasks` (`TenantId`, `WorkflowInstanceId`)";
            await cmd.ExecuteNonQueryAsync();
            logger.LogInformation("EnsureLiensSchemaTablesAsync: Created IX_Tasks_TenantId_WorkflowInstanceId.");
        }
        catch (Exception idxEx)
        {
            logger.LogWarning(idxEx, "EnsureLiensSchemaTablesAsync: Could not create IX_Tasks_TenantId_WorkflowInstanceId (may already exist).");
        }
    }
    else
    {
        logger.LogInformation("EnsureLiensSchemaTablesAsync: liens_Tasks flow-linkage columns already present.");
    }

    // LS-LIENS-CONTACT-DRIFT — ensure contact subtype linkage columns exist even
    // when startup migrations were skipped or partially failed. Without these
    // columns, simple list reads can fail with MySQL "Unknown column" errors.
    async Task<bool> HasContactColumnAsync(string columnName)
    {
        cmd.CommandText = $"""
            SELECT COUNT(*) FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'liens_Contacts'
              AND COLUMN_NAME  = '{columnName}'
            """;
        return Convert.ToInt64(await cmd.ExecuteScalarAsync()) > 0;
    }

    if (!await HasContactColumnAsync("ContactSubtype"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Contacts`
                ADD COLUMN `ContactSubtype` varchar(50) NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added ContactSubtype to liens_Contacts.");
    }

    if (!await HasContactColumnAsync("FacilityId"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Contacts`
                ADD COLUMN `FacilityId` char(36) NULL COLLATE ascii_general_ci
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added FacilityId to liens_Contacts.");
    }

    if (!await HasContactColumnAsync("LawFirmId"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Contacts`
                ADD COLUMN `LawFirmId` char(36) NULL COLLATE ascii_general_ci
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added LawFirmId to liens_Contacts.");
    }

    async Task<bool> HasContactIndexAsync(string indexName)
    {
        cmd.CommandText = $"""
            SELECT COUNT(*) FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'liens_Contacts'
              AND INDEX_NAME   = '{indexName}'
            """;
        return Convert.ToInt64(await cmd.ExecuteScalarAsync()) > 0;
    }

    if (!await HasContactIndexAsync("IX_Contacts_TenantId_FacilityId_ContactSubtype"))
    {
        cmd.CommandText = """
            CREATE INDEX `IX_Contacts_TenantId_FacilityId_ContactSubtype`
            ON `liens_Contacts` (`TenantId`, `FacilityId`, `ContactSubtype`)
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Created IX_Contacts_TenantId_FacilityId_ContactSubtype.");
    }

    if (!await HasContactIndexAsync("IX_Contacts_TenantId_LawFirmId_ContactSubtype"))
    {
        cmd.CommandText = """
            CREATE INDEX `IX_Contacts_TenantId_LawFirmId_ContactSubtype`
            ON `liens_Contacts` (`TenantId`, `LawFirmId`, `ContactSubtype`)
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Created IX_Contacts_TenantId_LawFirmId_ContactSubtype.");
    }

    // LS-LIENS-LIEN-DRIFT — ensure legacy medical fields exist for dashboard
    // exports against older dumps that predate migration 20260625000001.
    async Task<bool> HasLienColumnAsync(string columnName)
    {
        cmd.CommandText = $"""
            SELECT COUNT(*) FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'liens_Liens'
              AND COLUMN_NAME  = '{columnName}'
            """;
        return Convert.ToInt64(await cmd.ExecuteScalarAsync()) > 0;
    }

    if (!await HasLienColumnAsync("InitialServiceDate"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Liens`
                ADD COLUMN `InitialServiceDate` date NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added InitialServiceDate to liens_Liens.");
    }

    if (!await HasLienColumnAsync("EndServiceDate"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Liens`
                ADD COLUMN `EndServiceDate` date NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added EndServiceDate to liens_Liens.");
    }

    if (!await HasLienColumnAsync("IsBulk"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Liens`
                ADD COLUMN `IsBulk` varchar(10) NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added IsBulk to liens_Liens.");
    }

    if (!await HasLienColumnAsync("IsServicing"))
    {
        cmd.CommandText = """
            ALTER TABLE `liens_Liens`
                ADD COLUMN `IsServicing` varchar(10) NULL
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added IsServicing to liens_Liens.");
    }

    // LS-LIENS-OFFER-DRIFT — liens_LienOffers.SubmittedByPlatformUserId added by
    // migration 20260906010000_AddSellingNotificationInboxOutbox. When that
    // migration was skipped or only partially applied, every query that
    // materializes a LienOffer (e.g. the selling lien detail endpoint) fails with
    // a MySQL "Unknown column" error and returns 500 for all lien IDs.
    cmd.CommandText = """
        SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME   = 'liens_LienOffers'
          AND COLUMN_NAME  = 'SubmittedByPlatformUserId'
        """;
    if (Convert.ToInt64(await cmd.ExecuteScalarAsync()) == 0)
    {
        cmd.CommandText = """
            ALTER TABLE `liens_LienOffers`
                ADD COLUMN `SubmittedByPlatformUserId` char(36) NULL COLLATE ascii_general_ci
            """;
        await cmd.ExecuteNonQueryAsync();
        logger.LogInformation("EnsureLiensSchemaTablesAsync: Added SubmittedByPlatformUserId to liens_LienOffers.");
    }
}
